file_format: "1"
id: dactyl543
name: DACTYL543
type: shield
url: https://github.com/abstracthat/dactyl-manuform
requires: [nice_nano]
features:
  - keys
siblings:
  - dactyl543_left
  - dactyl543_right
